# Generated by Django 4.1.7 on 2023-03-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_initial"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="ledetail",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="lectures.calculatedlecture",
            ),
        ),
    ]
