# Generated by Django 4.1.7 on 2023-03-21 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_initial"),
        ("videos", "0002_alter_video_ledetail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="ledetail",
        ),
        migrations.AddField(
            model_name="video",
            name="calculatedLecture",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="lectures.calculatedlecture",
            ),
            preserve_default=False,
        ),
    ]
