# Generated by Django 4.1.7 on 2023-03-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
