# Generated by Django 4.1.7 on 2023-03-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ledetaile",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user",
                to="lectures.calculatedlecture",
            ),
        ),
    ]
