# Generated by Django 4.1.7 on 2023-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_initial"),
        ("users", "0002_alter_user_ledetaile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="ledetaile",
        ),
        migrations.AddField(
            model_name="user",
            name="calculatedLecture",
            field=models.ManyToManyField(
                blank=True, related_name="user", to="lectures.calculatedlecture"
            ),
        ),
    ]
