# Generated by Django 4.1.7 on 2023-03-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_withdrawn_at_user_created_at_user_iswithdrawn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("loginDate", models.DateTimeField(auto_now=True)),
                ("lectureDate", models.DateTimeField(auto_now=True)),
                ("paymentDate", models.DateTimeField(auto_now=True)),
                ("isWithdrawn", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("Withdrawn_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="Withdrawn_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="isWithdrawn",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lectureDate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="loginDate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="paymentDate",
        ),
        migrations.RemoveField(
            model_name="user",
            name="updated_at",
        ),
    ]
