# Generated by Django 4.1.7 on 2023-03-11 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        ("informations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="information",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="informations.information",
            ),
        ),
    ]
