# Generated by Django 4.1.7 on 2023-03-10 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("informations", "0002_remove_information_purchase"),
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activite",
            name="information",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="informations.information",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activite",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activite",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
