# Generated by Django 4.1.7 on 2023-03-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0001_initial"),
        ("lectures", "0002_lecture_user"),
        ("ledetailes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledetaile",
            name="lecture",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="lectures.lecture"
            ),
        ),
        migrations.AlterField(
            model_name="ledetaile",
            name="video",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="videos.video"
            ),
        ),
    ]
