# Generated by Django 4.1.7 on 2023-03-10 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0002_remove_video_lecture"),
        ("ledetailes", "0002_alter_ledetaile_lecture_alter_ledetaile_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledetaile",
            name="video",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video",
                to="videos.video",
            ),
        ),
    ]
