<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-11 15:17
=======
# Generated by Django 4.1.7 on 2023-03-11 08:26
>>>>>>> ae93117c55732368faf2d3dcf0f70039064211ab

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("informations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
