# Generated by Django 4.1.7 on 2023-03-10 07:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("informations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="information",
            name="purchase",
        ),
    ]
