# Generated by Django 4.1.7 on 2023-03-10 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("informations", "0002_remove_information_purchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="information",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
