# Generated by Django 4.1.7 on 2023-03-10 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ledetailes", "0001_initial"),
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ledetailes",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ledetailes.ledetaile",
            ),
            preserve_default=False,
        ),
    ]
