# Generated by Django 4.1.7 on 2023-03-15 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="author",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="author",
            new_name="user",
        ),
    ]
