# Generated by Django 4.1.7 on 2023-03-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_initial"),
        ("reviews", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="lecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="lectures.lecture",
            ),
        ),
    ]
