# Generated by Django 4.1.7 on 2023-03-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reply",
            old_name="reviews",
            new_name="review",
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
