# Generated by Django 4.1.7 on 2023-03-09 03:23

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 8635767911e5135e624b04e9ca1cd276aa801718


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
<<<<<<< HEAD
=======
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("LectureId", models.AutoField(primary_key=True, serialize=False)),
                ("lectureTitle", models.CharField(max_length=100)),
                ("lectureDescription", models.TextField(max_length=1000)),
                ("lectureDifficulty", models.CharField(max_length=100)),
                ("targetAudience", models.CharField(max_length=100)),
                ("lectureFee", models.PositiveIntegerField(blank=True, null=True)),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("lecturePeriod", models.DateField(blank=True, null=True)),
                ("isOpened", models.BooleanField(default=True)),
                ("likes", models.BooleanField(default=True)),
                ("lectureDuration", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "lectureTotal",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="calculatedLecture",
            fields=[
>>>>>>> 8635767911e5135e624b04e9ca1cd276aa801718
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ("lectureTitle", models.CharField(max_length=100)),
                ("lectureDescription", models.TextField(max_length=1000)),
                ("lectureDifficulty", models.CharField(max_length=100)),
                ("targetAudience", models.CharField(max_length=100)),
                ("lectureFee", models.PositiveIntegerField()),
                ("thumbnail", models.URLField()),
                ("lecturePeriod", models.DateField()),
                ("isOpened", models.BooleanField(default=True)),
                ("likes", models.BooleanField(default=True)),
                ("lectureDuration", models.PositiveIntegerField()),
                ("lectureTotal", models.CharField(max_length=100)),
=======
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecture_details",
                        to="lectures.lecture",
                    ),
                ),
>>>>>>> 8635767911e5135e624b04e9ca1cd276aa801718
            ],
            options={
                "abstract": False,
            },
        ),
    ]
