# Generated by Django 4.1.7 on 2023-03-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lectureTitle", models.CharField(max_length=100)),
                ("lectureDescription", models.TextField(max_length=1000)),
                ("lectureDifficulty", models.CharField(max_length=100)),
                ("targetAudience", models.CharField(max_length=100)),
                ("lectureFee", models.PositiveIntegerField()),
                ("thumbnail", models.URLField()),
                ("lecturePeriod", models.DateField()),
                ("isOpened", models.BooleanField(default=True)),
                ("likes", models.BooleanField(default=True)),
                ("lectureDuration", models.PositiveIntegerField()),
                ("lectureTotal", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
