# Generated by Django 4.1.7 on 2023-03-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="lectureDuration",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="lectureFee",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="lecturePeriod",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="lectureTotal",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
