# Generated by Django 4.1.7 on 2023-03-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="likes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
