# Generated by Django 4.1.7 on 2023-03-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="grade",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
