# Generated by Django 4.1.7 on 2023-03-13 04:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0003_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cart",
            new_name="Cartm",
        ),
    ]
