# Generated by Django 4.1.7 on 2023-03-13 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lectures", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0006_remove_cart_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="rating",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="lecture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to="lectures.lecture",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
