# Generated by Django 4.1.7 on 2023-03-10 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ledetailes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qnas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qna",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qnas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="qna",
            name="lecture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qna",
                to="ledetailes.ledetaile",
            ),
        ),
        migrations.AddField(
            model_name="qna",
            name="like_users",
            field=models.ManyToManyField(
                blank=True, related_name="like_qnas", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
